/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lendingPoolSol from "./LendingPool.sol";
export type { lendingPoolSol };
import type * as oracleSol from "./Oracle.sol";
export type { oracleSol };
export type { MockUSDC } from "./MockUSDC";
export type { OracleMock } from "./OracleMock";
export type { WETH9 } from "./WETH9";
