/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LendingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASE_RATE_BPS"
      | "BPS"
      | "CLOSE_FACTOR_BPS"
      | "LIQ_BONUS_BPS"
      | "LIQ_THRESHOLD_BPS"
      | "LTV_BPS"
      | "MIN_LIQUIDATION_USDC"
      | "MIN_LIQUIDATION_WETH"
      | "OPTIMAL_UTIL_BPS"
      | "ORACLE"
      | "RAY"
      | "RESERVE_FACTOR_BPS"
      | "SLOPE1_BPS"
      | "SLOPE2_BPS"
      | "USDC"
      | "WAD"
      | "WETH"
      | "YEAR"
      | "accrue"
      | "borrowIndex"
      | "borrowUSDC"
      | "collateralWETH"
      | "depositETH"
      | "depositUSDC"
      | "getBorrowMax"
      | "getBorrowRateBps"
      | "getHealthFactor"
      | "getUserAccountData"
      | "getUserDebtUSDC"
      | "getUserSupplyUSDC"
      | "getUtilizationBps"
      | "lastAccrual"
      | "liquidate"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "repayUSDC"
      | "rescueToken"
      | "reserveWad"
      | "scaledDebtUSDC"
      | "setOracle"
      | "setRateModel"
      | "setReserveFactor"
      | "setRiskParams"
      | "supplyShares"
      | "totalCollateralWETH"
      | "totalScaledDebt"
      | "totalSupplyShares"
      | "transferOwnership"
      | "unpause"
      | "withdrawETH"
      | "withdrawUSDC"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Accrue"
      | "Borrow"
      | "Deposit"
      | "Liquidate"
      | "OracleUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "RateModelUpdated"
      | "Repay"
      | "ReserveFactorUpdated"
      | "RiskParamsUpdated"
      | "SupplyUSDC"
      | "Unpaused"
      | "Withdraw"
      | "WithdrawUSDC"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASE_RATE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "CLOSE_FACTOR_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQ_BONUS_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQ_THRESHOLD_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "LTV_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "MIN_LIQUIDATION_USDC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LIQUIDATION_WETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTIMAL_UTIL_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ORACLE", values?: undefined): string;
  encodeFunctionData(functionFragment: "RAY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "RESERVE_FACTOR_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLOPE1_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLOPE2_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(functionFragment: "WAD", values?: undefined): string;
  encodeFunctionData(functionFragment: "WETH", values?: undefined): string;
  encodeFunctionData(functionFragment: "YEAR", values?: undefined): string;
  encodeFunctionData(functionFragment: "accrue", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "borrowIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrowUSDC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collateralWETH",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositUSDC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowMax",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowRateBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHealthFactor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAccountData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDebtUSDC",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserSupplyUSDC",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUtilizationBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastAccrual",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayUSDC",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveWad",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scaledDebtUSDC",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRateModel",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveFactor",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskParams",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyShares",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalCollateralWETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalScaledDebt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupplyShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawETH",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUSDC",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASE_RATE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "CLOSE_FACTOR_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQ_BONUS_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQ_THRESHOLD_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LTV_BPS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LIQUIDATION_USDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LIQUIDATION_WETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPTIMAL_UTIL_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ORACLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RAY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "RESERVE_FACTOR_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SLOPE1_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SLOPE2_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WAD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WETH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "YEAR", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "accrue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrowIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowUSDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collateralWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowMax",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowRateBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHealthFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAccountData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDebtUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserSupplyUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUtilizationBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastAccrual",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "liquidate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayUSDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rescueToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserveWad", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "scaledDebtUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRateModel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCollateralWETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalScaledDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupplyShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUSDC",
    data: BytesLike
  ): Result;
}

export namespace AccrueEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    utilizationBps: BigNumberish,
    rateBps: BigNumberish,
    interestAccruedWad: BigNumberish,
    reserveAccruedWad: BigNumberish,
    prevIndex: BigNumberish,
    newIndex: BigNumberish
  ];
  export type OutputTuple = [
    timestamp: bigint,
    utilizationBps: bigint,
    rateBps: bigint,
    interestAccruedWad: bigint,
    reserveAccruedWad: bigint,
    prevIndex: bigint,
    newIndex: bigint
  ];
  export interface OutputObject {
    timestamp: bigint;
    utilizationBps: bigint;
    rateBps: bigint;
    interestAccruedWad: bigint;
    reserveAccruedWad: bigint;
    prevIndex: bigint;
    newIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BorrowEvent {
  export type InputTuple = [user: AddressLike, usdcAmount: BigNumberish];
  export type OutputTuple = [user: string, usdcAmount: bigint];
  export interface OutputObject {
    user: string;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [user: AddressLike, ethAmount: BigNumberish];
  export type OutputTuple = [user: string, ethAmount: bigint];
  export interface OutputObject {
    user: string;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidateEvent {
  export type InputTuple = [
    liquidator: AddressLike,
    user: AddressLike,
    repayAmount: BigNumberish,
    seizedCollateral: BigNumberish
  ];
  export type OutputTuple = [
    liquidator: string,
    user: string,
    repayAmount: bigint,
    seizedCollateral: bigint
  ];
  export interface OutputObject {
    liquidator: string;
    user: string;
    repayAmount: bigint;
    seizedCollateral: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleUpdatedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RateModelUpdatedEvent {
  export type InputTuple = [
    baseRateBps: BigNumberish,
    slope1Bps: BigNumberish,
    slope2Bps: BigNumberish,
    optimalUtilBps: BigNumberish
  ];
  export type OutputTuple = [
    baseRateBps: bigint,
    slope1Bps: bigint,
    slope2Bps: bigint,
    optimalUtilBps: bigint
  ];
  export interface OutputObject {
    baseRateBps: bigint;
    slope1Bps: bigint;
    slope2Bps: bigint;
    optimalUtilBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepayEvent {
  export type InputTuple = [user: AddressLike, usdcAmount: BigNumberish];
  export type OutputTuple = [user: string, usdcAmount: bigint];
  export interface OutputObject {
    user: string;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveFactorUpdatedEvent {
  export type InputTuple = [reserveFactorBps: BigNumberish];
  export type OutputTuple = [reserveFactorBps: bigint];
  export interface OutputObject {
    reserveFactorBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskParamsUpdatedEvent {
  export type InputTuple = [
    ltvBps: BigNumberish,
    liqThresholdBps: BigNumberish
  ];
  export type OutputTuple = [ltvBps: bigint, liqThresholdBps: bigint];
  export interface OutputObject {
    ltvBps: bigint;
    liqThresholdBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyUSDCEvent {
  export type InputTuple = [
    user: AddressLike,
    usdcAmount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [user: string, usdcAmount: bigint, shares: bigint];
  export interface OutputObject {
    user: string;
    usdcAmount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [user: AddressLike, ethAmount: BigNumberish];
  export type OutputTuple = [user: string, ethAmount: bigint];
  export interface OutputObject {
    user: string;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawUSDCEvent {
  export type InputTuple = [
    user: AddressLike,
    usdcAmount: BigNumberish,
    shares: BigNumberish
  ];
  export type OutputTuple = [user: string, usdcAmount: bigint, shares: bigint];
  export interface OutputObject {
    user: string;
    usdcAmount: bigint;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LendingPool extends BaseContract {
  connect(runner?: ContractRunner | null): LendingPool;
  waitForDeployment(): Promise<this>;

  interface: LendingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASE_RATE_BPS: TypedContractMethod<[], [bigint], "view">;

  BPS: TypedContractMethod<[], [bigint], "view">;

  CLOSE_FACTOR_BPS: TypedContractMethod<[], [bigint], "view">;

  LIQ_BONUS_BPS: TypedContractMethod<[], [bigint], "view">;

  LIQ_THRESHOLD_BPS: TypedContractMethod<[], [bigint], "view">;

  LTV_BPS: TypedContractMethod<[], [bigint], "view">;

  MIN_LIQUIDATION_USDC: TypedContractMethod<[], [bigint], "view">;

  MIN_LIQUIDATION_WETH: TypedContractMethod<[], [bigint], "view">;

  OPTIMAL_UTIL_BPS: TypedContractMethod<[], [bigint], "view">;

  ORACLE: TypedContractMethod<[], [string], "view">;

  RAY: TypedContractMethod<[], [bigint], "view">;

  RESERVE_FACTOR_BPS: TypedContractMethod<[], [bigint], "view">;

  SLOPE1_BPS: TypedContractMethod<[], [bigint], "view">;

  SLOPE2_BPS: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  WAD: TypedContractMethod<[], [bigint], "view">;

  WETH: TypedContractMethod<[], [string], "view">;

  YEAR: TypedContractMethod<[], [bigint], "view">;

  accrue: TypedContractMethod<[], [void], "nonpayable">;

  borrowIndex: TypedContractMethod<[], [bigint], "view">;

  borrowUSDC: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  collateralWETH: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  depositETH: TypedContractMethod<[], [void], "payable">;

  depositUSDC: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBorrowMax: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getBorrowRateBps: TypedContractMethod<[], [bigint], "view">;

  getHealthFactor: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserAccountData: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        collateralUsdWad: bigint;
        debtUsdWad: bigint;
        borrowMaxUsdc: bigint;
        healthFactorWad: bigint;
      }
    ],
    "view"
  >;

  getUserDebtUSDC: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserSupplyUSDC: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUtilizationBps: TypedContractMethod<[], [bigint], "view">;

  lastAccrual: TypedContractMethod<[], [bigint], "view">;

  liquidate: TypedContractMethod<
    [user: AddressLike, repayAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayUSDC: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  rescueToken: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  reserveWad: TypedContractMethod<[], [bigint], "view">;

  scaledDebtUSDC: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setOracle: TypedContractMethod<[oracle_: AddressLike], [void], "nonpayable">;

  setRateModel: TypedContractMethod<
    [
      baseRateBps_: BigNumberish,
      slope1Bps_: BigNumberish,
      slope2Bps_: BigNumberish,
      optimalUtilBps_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setReserveFactor: TypedContractMethod<
    [reserveFactorBps_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRiskParams: TypedContractMethod<
    [ltvBps_: BigNumberish, liqThresholdBps_: BigNumberish],
    [void],
    "nonpayable"
  >;

  supplyShares: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalCollateralWETH: TypedContractMethod<[], [bigint], "view">;

  totalScaledDebt: TypedContractMethod<[], [bigint], "view">;

  totalSupplyShares: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdrawETH: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawUSDC: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASE_RATE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CLOSE_FACTOR_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIQ_BONUS_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LIQ_THRESHOLD_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "LTV_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LIQUIDATION_USDC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LIQUIDATION_WETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OPTIMAL_UTIL_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESERVE_FACTOR_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLOPE1_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLOPE2_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WAD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "YEAR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "accrue"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "borrowIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "borrowUSDC"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collateralWETH"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositETH"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "depositUSDC"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBorrowMax"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBorrowRateBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHealthFactor"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserAccountData"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        collateralUsdWad: bigint;
        debtUsdWad: bigint;
        borrowMaxUsdc: bigint;
        healthFactorWad: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDebtUSDC"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserSupplyUSDC"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUtilizationBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastAccrual"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidate"
  ): TypedContractMethod<
    [user: AddressLike, repayAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayUSDC"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueToken"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveWad"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "scaledDebtUSDC"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setOracle"
  ): TypedContractMethod<[oracle_: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRateModel"
  ): TypedContractMethod<
    [
      baseRateBps_: BigNumberish,
      slope1Bps_: BigNumberish,
      slope2Bps_: BigNumberish,
      optimalUtilBps_: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveFactor"
  ): TypedContractMethod<
    [reserveFactorBps_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRiskParams"
  ): TypedContractMethod<
    [ltvBps_: BigNumberish, liqThresholdBps_: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supplyShares"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCollateralWETH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalScaledDebt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupplyShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawETH"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUSDC"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Accrue"
  ): TypedContractEvent<
    AccrueEvent.InputTuple,
    AccrueEvent.OutputTuple,
    AccrueEvent.OutputObject
  >;
  getEvent(
    key: "Borrow"
  ): TypedContractEvent<
    BorrowEvent.InputTuple,
    BorrowEvent.OutputTuple,
    BorrowEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Liquidate"
  ): TypedContractEvent<
    LiquidateEvent.InputTuple,
    LiquidateEvent.OutputTuple,
    LiquidateEvent.OutputObject
  >;
  getEvent(
    key: "OracleUpdated"
  ): TypedContractEvent<
    OracleUpdatedEvent.InputTuple,
    OracleUpdatedEvent.OutputTuple,
    OracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RateModelUpdated"
  ): TypedContractEvent<
    RateModelUpdatedEvent.InputTuple,
    RateModelUpdatedEvent.OutputTuple,
    RateModelUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Repay"
  ): TypedContractEvent<
    RepayEvent.InputTuple,
    RepayEvent.OutputTuple,
    RepayEvent.OutputObject
  >;
  getEvent(
    key: "ReserveFactorUpdated"
  ): TypedContractEvent<
    ReserveFactorUpdatedEvent.InputTuple,
    ReserveFactorUpdatedEvent.OutputTuple,
    ReserveFactorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RiskParamsUpdated"
  ): TypedContractEvent<
    RiskParamsUpdatedEvent.InputTuple,
    RiskParamsUpdatedEvent.OutputTuple,
    RiskParamsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SupplyUSDC"
  ): TypedContractEvent<
    SupplyUSDCEvent.InputTuple,
    SupplyUSDCEvent.OutputTuple,
    SupplyUSDCEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawUSDC"
  ): TypedContractEvent<
    WithdrawUSDCEvent.InputTuple,
    WithdrawUSDCEvent.OutputTuple,
    WithdrawUSDCEvent.OutputObject
  >;

  filters: {
    "Accrue(uint256,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      AccrueEvent.InputTuple,
      AccrueEvent.OutputTuple,
      AccrueEvent.OutputObject
    >;
    Accrue: TypedContractEvent<
      AccrueEvent.InputTuple,
      AccrueEvent.OutputTuple,
      AccrueEvent.OutputObject
    >;

    "Borrow(address,uint256)": TypedContractEvent<
      BorrowEvent.InputTuple,
      BorrowEvent.OutputTuple,
      BorrowEvent.OutputObject
    >;
    Borrow: TypedContractEvent<
      BorrowEvent.InputTuple,
      BorrowEvent.OutputTuple,
      BorrowEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Liquidate(address,address,uint256,uint256)": TypedContractEvent<
      LiquidateEvent.InputTuple,
      LiquidateEvent.OutputTuple,
      LiquidateEvent.OutputObject
    >;
    Liquidate: TypedContractEvent<
      LiquidateEvent.InputTuple,
      LiquidateEvent.OutputTuple,
      LiquidateEvent.OutputObject
    >;

    "OracleUpdated(address)": TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;
    OracleUpdated: TypedContractEvent<
      OracleUpdatedEvent.InputTuple,
      OracleUpdatedEvent.OutputTuple,
      OracleUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RateModelUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      RateModelUpdatedEvent.InputTuple,
      RateModelUpdatedEvent.OutputTuple,
      RateModelUpdatedEvent.OutputObject
    >;
    RateModelUpdated: TypedContractEvent<
      RateModelUpdatedEvent.InputTuple,
      RateModelUpdatedEvent.OutputTuple,
      RateModelUpdatedEvent.OutputObject
    >;

    "Repay(address,uint256)": TypedContractEvent<
      RepayEvent.InputTuple,
      RepayEvent.OutputTuple,
      RepayEvent.OutputObject
    >;
    Repay: TypedContractEvent<
      RepayEvent.InputTuple,
      RepayEvent.OutputTuple,
      RepayEvent.OutputObject
    >;

    "ReserveFactorUpdated(uint256)": TypedContractEvent<
      ReserveFactorUpdatedEvent.InputTuple,
      ReserveFactorUpdatedEvent.OutputTuple,
      ReserveFactorUpdatedEvent.OutputObject
    >;
    ReserveFactorUpdated: TypedContractEvent<
      ReserveFactorUpdatedEvent.InputTuple,
      ReserveFactorUpdatedEvent.OutputTuple,
      ReserveFactorUpdatedEvent.OutputObject
    >;

    "RiskParamsUpdated(uint256,uint256)": TypedContractEvent<
      RiskParamsUpdatedEvent.InputTuple,
      RiskParamsUpdatedEvent.OutputTuple,
      RiskParamsUpdatedEvent.OutputObject
    >;
    RiskParamsUpdated: TypedContractEvent<
      RiskParamsUpdatedEvent.InputTuple,
      RiskParamsUpdatedEvent.OutputTuple,
      RiskParamsUpdatedEvent.OutputObject
    >;

    "SupplyUSDC(address,uint256,uint256)": TypedContractEvent<
      SupplyUSDCEvent.InputTuple,
      SupplyUSDCEvent.OutputTuple,
      SupplyUSDCEvent.OutputObject
    >;
    SupplyUSDC: TypedContractEvent<
      SupplyUSDCEvent.InputTuple,
      SupplyUSDCEvent.OutputTuple,
      SupplyUSDCEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;

    "WithdrawUSDC(address,uint256,uint256)": TypedContractEvent<
      WithdrawUSDCEvent.InputTuple,
      WithdrawUSDCEvent.OutputTuple,
      WithdrawUSDCEvent.OutputObject
    >;
    WithdrawUSDC: TypedContractEvent<
      WithdrawUSDCEvent.InputTuple,
      WithdrawUSDCEvent.OutputTuple,
      WithdrawUSDCEvent.OutputObject
    >;
  };
}
